proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /app/seuratApp
  port: 8080
  authentication: none
  hide-navbar: true
  container-log-path: /etc/shinyproxy/container-logs
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  # - id: 01_hello
  #   display-name: Hello Application
  #   description: Application which demonstrates the basics of a Shiny app
  #   container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
  #   container-image: openanalytics/shinyproxy-demo
  #   container-network: sp-example-net
  # - id: 06_tabsets
  #   container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
  #   container-image: openanalytics/shinyproxy-demo
  #   container-network: sp-example-net
  - id: euler
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: cobriniklab405/seurattools
    access-groups: admins
    container-volumes: ["/dataVolume/storage/single_cell_projects/shinyproxy/dockerdata:/root/dockerdata"]
    container-network: seurattools-net
  - id: seuratApp
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/seuratApp/app.R')"]
    container-image: cobriniklab405/seurattools
    access-groups: scientists
    container-volumes: ["/dataVolume/storage/single_cell_projects/shinyproxy/dockerdata:/root/dockerdata"]
    container-network: seurattools-net

logging: >-->---
  file:
    name: shinyproxy.log